import { backendApi } from '@/api/backendApi';
import type { Client } from '@/interfaces/client.interface';

export const getClientByIdAction = async (id: string): Promise<Client> => {
  if (!id) throw new Error('Id is required');

  if (id === 'new') {
    return {
      id: 'new',
        usuario_creador: '',
        fecha_creacion: undefined,
        usuario_actualizador: '',
        fecha_actualizacion: undefined,
        es_activo: true,
        nombres: '',
        apellidos: '',
        sexo: '',
        fecha_nacimiento: undefined,
        estado_civil: '',
        nacimiento_codigo: '',
        paga_viaje_quien: '',
        paga_viaje_nombres: '',
        paga_viaje_apellidos: '',
        paga_viaje_telefono: '',
        paga_viaje_correo: '',
        paga_viaje_relacion: '',
        paga_viaje_direccion: '',
        paga_viaje_codigo: '',
        paga_viaje_viven_juntos: '',
        id_viajes_usa: [],
        huellas_digitales: false,
        licencia_usa: '',
        id_visa: '',
        rechazo_anterior: false,
        rechazo_descripcion: '',
        solicita_residencia_usa: false,
        residencia_direccion: '',
        residencia_codigo: '',
        telefonos: [],
        trabajo_telefono: '',
        correo_electronico: '',
        pasaporte_numero: '',
        pasaporte_libreta: '',
        pasaporte_lugar_emision: '',
        pasaporte_fecha_emision: undefined,
        pasaporte_fecha_expiracion: undefined,
        pasaporte_extraviado: false,
        padre_nombres: '',
        padre_apellidos: '',
        padre_fecha_nacimiento: undefined,
        padre_estatus_usa: '',
        madre_nombres: '',
        madre_apellidos: '',
        madre_fecha_nacimiento: undefined,
        madre_estatus_usa: '',
        id_familiares_usa: [],
        familiares_lejanos: false,
        conyuge_apellidos: '',
        conyuge_nombres: '',
        conyuge_fecha_nacimiento: undefined,
        conyuge_municipio_nacimiento: '',
        conyuge_departamento_nacimiento: '',
        conyuge_direccion: '',
        conyuge_codigo: '',
        conyuge_fecha_separacion: undefined,
        conyuge_fecha_fallecimiento: undefined,
        trabajo_tipo: '',
        trabajo_empresa: '',
        trabajo_direccion: '',
        trabajo_codigo: '',
        trabajo_salario: '',
        trabajo_fecha: undefined,
        trabajo_descripcion: '',
        id_idiomas: [],
        educacion_nombre: '',
        educacion_direccion: '',
        educacion_carrera: '',
        educacion_fecha_inicio: undefined,
        educacion_fecha_fin: undefined,
        educacion_telefono: '',
        educacion_codigo: '',
        ultimos_viajes: [],
        armas: '',
        id_ds160: [],
        redes_sociales: [],
    } as unknown as Client;
  }

  const { data } = await backendApi.get<Client>(`?info=clientes&id=${id}`);

  return {
    ...data,
  };
};