

export interface Client {
  id:                          string;
    usuario_creador:             string;
    fecha_creacion:              Date | undefined;
    usuario_actualizador:        string;
    fecha_actualizacion:         Date | undefined;
    es_activo:                   boolean;
    nombres:                     string;
    apellidos:                   string;
    sexo:                        "M"|"F";
    estado_civil:                string;
    fecha_nacimiento:            Date | undefined;
    nacimiento_codigo:           string;
    pasaporte_numero:            string;
    pasaporte_libreta:           string;
    pasaporte_lugar_emision:     string;
    pasaporte_fecha_emision:     Date | undefined;
    pasaporte_fecha_expiracion:  Date | undefined;
    pasaporte_extraviado:        string;
    correo_electronico:          string;
    telefonos:                   string[];
    residencia_direccion:        string;
    residencia_codigo:           string;
    
    paga_viaje_quien:            string;
    paga_viaje_nombres:          string;
    paga_viaje_apellidos:        string;
    paga_viaje_telefono:         string;
    paga_viaje_correo:           string;
    paga_viaje_relacion:         string;
    paga_viaje_direccion:        string;
    paga_viaje_codigo:           string;
    paga_viaje_viven_juntos:     string;
    id_viajes_usa:               string;
    huellas_digitales:           string;
    licencia_usa:                string;
    id_visa:                     string;
    rechazo_anterior:            string;
    rechazo_descripcion:         string;
    solicita_residencia_usa:     string;
    trabajo_telefono:            string;
    padre_nombres:               string;
    padre_apellidos:             string;
    padre_fecha_nacimiento:      Date | undefined;
    padre_estatus_usa:           string;
    madre_nombres:               string;
    madre_apellidos:             string;
    madre_fecha_nacimiento:      Date | undefined;
    madre_estatus_usa:           string;
    id_familiares_usa:           string;
    familiares_lejanos:          string;
    conyuge_apellidos:           string;
    conyuge_nombres:             string;
    conyuge_fecha_nacimiento:    Date | undefined;
    conyuge_nacimiento_codigo:   string;
    conyuge_direccion:           string;
    conyuge_codigo:              string;
    conyuge_fecha_separacion:    Date | undefined;
    conyuge_fecha_fallecimiento: Date | undefined;
    trabajo_tipo:                string;
    trabajo_empresa:             string;
    trabajo_direccion:           string;
    trabajo_codigo:              string;
    trabajo_salario:             string;
    trabajo_fecha:               Date | undefined;
    trabajo_descripcion:         string;
    id_idiomas:                  string;
    educacion_nombre:            string;
    educacion_direccion:         string;
    educacion_carrera:           string;
    educacion_fecha_inicio:      Date | undefined;
    educacion_fecha_fin:         Date | undefined;
    educacion_telefono:          string;
    educacion_codigo:            string;
    ultimos_viajes:              string;
    armas:                       string;
    id_ds160:                    string;
    redes_sociales:              string;
}
